routes/admin.php
<?php

Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
Route::get('/rss', ['uses' => 'AdminController@rss', 'as' => 'admin.rss']);
Route::post('/rss/{id}/restore', ['uses' => 'RssController@restore', 'as' => 'rss.restore']);
Route::get('/rss/{id}/show', ['uses' => 'RssController@show', 'as' => 'rss.show']);
Route::resource('rss', 'RssController', ['except' => ['show', 'index']]);

routes/web.php
<?php

Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
Auth::routes();

app/Rss.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Rss
 * @package App
 */
class Rss extends Model
{
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'rss';

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $fillable = [
        'user_id',
        'name',
        'url'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 * @package App
 */
class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rss()
    {
        return $this->hasMany(Rss::class);
    }
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Repositories\RssRepository;

/**
 * Class AdminController
 * @package App\Http\Controllers\Admin
 */
class AdminController extends Controller
{
    protected $rssRepository;

    /**
     * AdminController constructor.
     * @param RssRepository $rssRepository
     */
    public function __construct(RssRepository $rssRepository)
    {
        $this->rssRepository = $rssRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function rss()
    {
        $rsses = $this->rssRepository->findAllByUserId($this->getAuthUser()->id);

        return view('admin.rss', compact('rsses'));
    }
}

app/Http/Controllers/Admin/RssController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Repositories\RssRepository;
use App\Rss;
use App\Services\RssService;
use Illuminate\Http\Request;

/**
 * Class RssController
 * @package App\Http\Controllers\Admin
 */
class RssController extends Controller
{
    /** @var RssRepository */
    protected $rssRepository;

    /** @var RssService */
    protected $rssService;

    /**
     * RssController constructor.
     * @param RssRepository $rssRepository
     * @param RssService $rssService
     */
    public function __construct(RssRepository $rssRepository, RssService $rssService)
    {
        $this->rssRepository = $rssRepository;
        $this->rssService = $rssService;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.rss.create');
    }

    /**
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validateRssForm($request);

        if ($this->rssRepository->create($request)) {
            return redirect('admin/rss')->with('success', 'Rss ' . $request['name'] . 'Created successfully');
        } else {
            return redirect('admin/rss')->withErrors('Rss ' . $request['name'] . 'Create failed');
        }
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $rss = Rss::findOrFail($id);
        $redirect = route('admin.rss');

        if (request()->has('redirect')) {
            $redirect = request()->input('redirect');
        }

        if ($rss->trashed()) {
            $result = $rss->forceDelete();
        } else {
            $result = $rss->delete();
        }

        if ($result) {
            return redirect($redirect)->with('success', 'Deleted successful');
        } else {
            return redirect($redirect)->withErrors('Delete Failed');
        }
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function restore($id)
    {
        $rss = Rss::findOrFail($id);

        if ($rss->trashed()) {
            $rss->restore();
            return redirect()->route('admin.rss')->with('success', 'Recovery successful');
        }
        return redirect()->route('admin.rss')->withErrors('Recovery failed');
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        /** @var Rss $rss */
        $rss = Rss::find($id);

        if ($rss->user_id != $this->getAuthUser()->id) {
            return redirect()->route('admin.rss')->withErrors('Invalid Permission');
        }

        return view('admin.rss.edit', compact('rss'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $this->validateRssForm($request);

        /** @var Rss $rss */
        $rss = Rss::find($id);

        if ($rss->user_id != $this->getAuthUser()->id) {
            return redirect()->route('admin.rss')->withErrors('Invalid Permission');
        }


        if ($this->rssRepository->update($request, $rss)) {
            return redirect()->route('admin.rss')->with('success', 'Updated successful');
        } else {
            return redirect()->route('admin.rss')->with('success', 'Updating failed');
        }
    }

    /**
     * @param int $rssId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(int $rssId)
    {
        /** @var Rss $rss */
        $rss = Rss::find($rssId);

        $channel = $this->rssService->getChannel($rss->url);
        $rsses = $this->rssRepository->findAllByUserId($this->getAuthUser()->id);

        return view('admin.rss.show', compact('channel', 'rsses'));
    }

    /**
     * @param Request $request
     */
    private function validateRssForm(Request $request)
    {
        $v = [
            'name' => 'required',
            'url' => 'required',
        ];

        $this->validate($request, $v);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    /**
     * @return \Illuminate\Contracts\Auth\Authenticatable|null
     */
    public function getAuthUser()
    {
        return auth()->user();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    public function index()
    {
        return view('index');
    }
}

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="theme-color" content="#52768e">
    <title>@yield('title')</title>
    <link href="{{ mix('css/admin.css') }}" rel="stylesheet">
    @yield('css')
    <script>
        window.RssConfig = <?php echo json_encode([
            'csrfToken' => csrf_token()
        ]);?>
    </script>
</head>
<body>
<div class="main">
    <div class="sidebar-wrapper bg-placeholder" id="sidebar-wrapper">
        <div class="p-3">
            <div class="collapse sidebar" id="sidebar">
                <?php
                $menus = [
                    [
                        'name' => 'Rss',
                        'icon' => 'list-alt',
                        'route' => 'admin.rss'
                    ],
                    [
                        'name' => 'Add Rss',
                        'icon' => 'plus',
                        'route' => 'rss.create'
                    ]
                ]
                ?>
                <div class="nav-wrapper">
                    <nav class="nav flex-column nav-pills font-weight-bold">
                        @foreach( $menus as $menu)
                            @if(isset($menu['is_parent']) && $menu['is_parent'])
                                <?php
                                foreach ($menu['children'] as $children_menu) {
                                    if (route($children_menu['route']) == request()->url()) {
                                        $show = true;
                                        break;
                                    } else
                                        $show = false;
                                }
                                ?>
                                <a class="nav-link{{ $show ? ' active':' collapsed' }}" role="tab" data-toggle="collapse" href="#{{ $menu['name'] }}" aria-expanded="false">
                                    <i class="fa fa-{{ $menu['icon'] }} fa-fw mr-3"></i>
                                    {{ $menu['name'] }}
                                </a>
                                <div class="collapse {{ $show ? ' show':'' }}" id="{{ $menu['name'] }}">
                                    <div class="nav-wrapper">
                                        <nav class="nav nav-pills flex-column">
                                            @foreach( $menu['children'] as $children_menu)
                                                <?php $link = route($children_menu['route']);?>
                                                <a class="ml-3 my-1 nav-link {{ $link == request()->url() ? ' active':'' }}" role="tab" href="{{ $link }}">
                                                    <i class="fa fa-{{ $children_menu['icon'] }} fa-fw mr-3"></i>
                                                    {{ $children_menu['name'] }}
                                                </a>
                                            @endforeach
                                        </nav>
                                    </div>
                                </div>
                            @else
                                <?php $link = route($menu['route']);?>
                                <a class="nav-link {{ $link == request()->url() ? ' active':'' }}" role="tab" href="{{ $link }}">
                                    <i class="fa fa-{{ $menu['icon'] }} fa-fw mr-3"></i>
                                    {{ $menu['name'] }}
                                </a>
                            @endif
                        @endforeach
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="content-wrapper">
        <nav class="navbar navbar-expand-lg navbar-light bg-light pt-1 pb-1" style="font-size: 85%">
            <?php $user = auth()->user();?>
            <a class="navbar-brand" href="{{ route('admin.index') }}">
                {{ $user->name }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="width: 1.25rem;height: 1.25rem;"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                            Logout
                        </a>
                    </li>
                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </ul>
            </div>
        </nav>
        <div class="pt-3 pr-3 pl-3">
            <div class="content-header">
                <div class="content-header-title">
                    <h2 class="content-header-title-det mt-0">@yield('title')</h2>
                </div>
                <div class="content-header-action">
                    @yield('action')
                </div>
            </div>
            <hr class="divider mt-3">
        </div>
        <div class="p-3">
            @include('partials.msg')
            @yield('content')
        </div>
    </div>
</div>

<script src="{{ mix('js/app.js') }}"></script>
@yield('script')
</body>
</html>

resources/views/admin/rss.blade.php
@extends('admin.layouts.app')
@section('title','Rss')
@section('content')
    <table class="table table-striped table-responsive">
        <thead>
        <tr>
            <th>Name</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($rsses as $rss)
            <tr>
                <td title="{{ $rss->name }}">{{ str_limit($rss->name,64) }}</td>
                <td>
                    <div>
                        <a {{ $rss->trashed()?'disabled':'' }} href="{{ $rss->trashed()?'javascript:void(0)':route('rss.edit',$rss->id) }}"
                           data-toggle="tooltip" data-placement="top" title="Edit"
                           class="btn btn-info">
                            <i class="fa fa-pencil fa-fw"></i>
                        </a>
                        @if($rss->trashed())
                            <form style="display: inline" method="post" action="{{ route('rss.restore',$rss->id) }}">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-primary" data-toggle="tooltip"
                                        data-placement="top" title="Restore">
                                    <i class="fa fa-repeat fa-fw"></i>
                                </button>
                            </form>
                        @else
                            <a href="{{ route('rss.show',$rss->id) }}" data-toggle="tooltip"
                               data-placement="top" title="Show"
                               class="btn btn-success">
                                <i class="fa fa-eye fa-fw"></i>
                            </a>
                        @endif
                        <button class="btn btn-danger swal-dialog-target"
                                data-toggle="tooltip"
                                data-title="{{ $rss->name }}"
                                data-dialog-msg="Do you want to delete <label>{{ $rss->name }}</label>？"
                                title="Delete"
                                data-dialog-enable-html="1"
                                data-url="{{ route('rss.destroy',$rss->id) }}"
                                data-dialog-confirm-text="{{ $rss->trashed()?'Delete (this will be permanently deleted)':'Delete' }}">
                            <i class="fa fa-trash-o  fa-fw"></i>
                        </button>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/rss/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Rss create')
@section('content')
    <div class="edit-form">
        <form class="form-horizontal" action="{{ route('rss.store') }}" method="post">
            @include('admin.rss.form-content')
            <button type="submit" class="btn btn-primary">
                Create
            </button>
        </form>
    </div>
@endsection

resources/views/admin/rss/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Edit ' . $rss->title)
@section('content')
    <div id="data" data-id="{{ $rss->id }}">
        <div class="card-body edit-form">
            <form role="form" class="form-horizontal" action="{{ route('rss.update', $rss->id) }}"
                  method="post">
                @include('admin.rss.form-content')
                <input type="hidden" name="_method" value="put">
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/rss/form-content.blade.php
<div class="form-group">
    <label for="name" class="form-control-label">Name*</label>
    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"
           value="{{ isset($rss) ? $rss->name : old('name') }}"
           autofocus>
    @if ($errors->has('name'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('name') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <label for="url" class="form-control-label">Url*</label>
    <input id="url" type="text" class="form-control{{ $errors->has('url') ? ' is-invalid' : '' }}" name="url"
           value="{{ isset($rss) ? $rss->url : old('url') }}"
           autofocus>
    @if ($errors->has('url'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('url') }}</strong>
        </div>
    @endif
</div>
{{ csrf_field() }}

resources/views/admin/rss/item.blade.php
<article class="post card">
    <!-- post header -->
    <div class="post-header">
        <h1 class="post-title">
            <a title="{{ $item->title }}" href="{{ $item->link }}">
                {{ $item->title }}
            </a>
        </h1>
        <div class="post-meta">
                           <span class="post-time">
                           <i class="fa fa-calendar-o"></i>
                           <time datetime="2016-08-05T00:10:14+08:00">
                           {{ $item->pubDate }}
                           </time>
                           </span>
            @if($item->thumbnail)
                <img src={{ $item->thumbnail->url }} class="img-fluid">
            @endif

        </div>
    </div>
    {{--post content--}}
    <div class="post-description">
        {!! $item->description !!}
    </div>
</article>

resources/views/admin/rss/show.blade.php
@extends('layouts.app')
@section('title','Rss feed')
@section('channel')
    {{ $channel->title }}
@stop
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                @if(!$channel->items)
                    <h3 class="meta-item center-block">NO POSTS.</h3>
                @else
                    @each('admin.rss.item',$channel->items,'item')
                @endif
            </div>
            <div class="col-md-4">
                <div class="slide">
                    @include('layouts.widgets')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.plain')
@section('content')
    <div class="home-box">
        <h3 title="Rss Application" aria-hidden="true" style="margin: 0">
            Rss Application
        </h3>
        <p class="links">
            <font aria-hidden="true">»</font>
            <a href="{{ route('login') }}" aria-label="Please login">Please login</a>
        </p>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en" xmlns:v-on="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#52768e">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    @yield('css')
    <script>
        window.RssConfig = <?php echo json_encode([
                'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body id="body">
@include('layouts.header')
<div id="content-wrap">
    <div class="container">
        @includeWhen(!isset($include_msg) || $include_msg, 'partials.msg')
    </div>
    @yield('content')
</div>
@include('layouts.footer')
<script src="{{ mix('js/app.js') }}"></script>
@yield('script')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer" id="footer">
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <span>Copyright © Kovacevic Denis</span> |
                    <span>Powered by Laravel</span>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<header class="main-header bg-placeholder">
    <div class="container-fluid" style="margin-top: -15px">
        <nav class="navbar navbar-dark navbar-expand-lg">
            <a href="/" id="blog-navbar-brand" class="navbar-brand">Rss Application</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse"
                    data-target="#blog-navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="blog-navbar-collapse">
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    @if(Auth::check())
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">
                                <?php
                                $user = auth()->user();
                                ?>
                                {{ $user->name }}
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ route('admin.rss') }}">Dashboard</a>
                                <a class="dropdown-item" href="{{ url('/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                    Logout
                                </a>
                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                    @else
                        <li class="nav-item"><a class="nav-link" href="{{ url('login') }}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url('register') }}">Register</a></li>
                    @endif

                </ul>
            </div>
        </nav>
    </div>
    <div class="container-fluid">
        <div class="description">@yield('channel')</div>
    </div>
</header>

resources/views/layouts/plain.blade.php
<!DOCTYPE html>
<html lang="en" xmlns:v-on="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="{{ $author or '' }}">
    <title>@yield('title') {{ $site_title or '' }} </title>
    <meta name="keywords" content="{{ $site_keywords or '' }}">
    <meta name="description" content="@yield('description') {{ $site_description or '' }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ $site_title or '' }}">
    <meta property="og:site_name" content="{{ $site_title or '' }}">
    <meta property="og:description" content="{{ $site_description or '' }}">
    <meta name="theme-color" content="#52768e">
    <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ mix('css/home.css') }}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="content">
        @yield('content')
    </div>
</div>
@yield('js')
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"></script>
</body>
</html>

resources/views/layouts/widgets.blade.php
@include('widget.rss_list')

resources/views/partials/empty.blade.php
<div class="card">
    <div class="card-body text-center">
        <h4 class="card-title">No data.</h4>
    </div>
</div>

resources/views/partials/msg.blade.php
@if (session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {!! session()->get('success') !!}
        </strong>
    </div>
@endif
@if(isset($errors)&&count($errors) > 0)
    <div class="alert alert-dismissible alert-danger fade show">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @if(count($errors) == 1)
            <strong>{!! $errors->first() !!}</strong>
        @else
            @foreach ($errors->all() as $error)
                <li><strong>{!! $error !!}</strong></li>
            @endforeach
        @endif

    </div>
@endif

resources/views/widget/rss_list.blade.php
<div class="card mb-3">
    <div class="card-header bg-white"><i class="fa fa-folder fa-fw"></i><a class="text-dark" href="{{ route('admin.rss') }}">All Rss</a></div>
    <div class="card-body">
        <div class="list-group hot-posts">
            @forelse($rsses as $rss)
                <a title="{{ $rss->name }}" href="{{ route('rss.show',$rss->id) }}"
                   class="list-group-item list-group-item-action">
                    {{ $rss->name }}
                </a>
            @empty
                <p class="meta-item center-block">No Rss Feeds.</p>
            @endforelse
        </div>
    </div>
</div>